# D:\XAU_Bot\config.yaml
execution:
  mode: live               # must be "live" for demo trading
  magic: 51001
  max_retries: 2
  default_slippage_pts: 100
  heartbeat_pipe: runtime/execution_heartbeat.json

engine:
  bar_seconds: 60

symbols:
  metals: ["XAUUSD.sd"] 
risk:
  sl_atr_mult: 1.5
  tp_atr_mult: 2.2
